//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Passenger
    {
        public int P_No { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public Nullable<int> Phone { get; set; }
    }
}
